title: Landing Page

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          hero_kicker:
            label: Hero Kicker
            type: text
            width: 1/2
          hero_title:
            label: Hero Titel
            type: text
          hero_intro:
            label: Hero Text
            type: textarea
            size: large
          spotlight_label:
            label: Highlight Label
            type: text
            width: 1/2
          spotlight_text:
            label: Highlight Text
            type: textarea
            size: medium
          upcoming_title:
            label: Nächster Auftritt – Titel
            type: text
          upcoming_date:
            label: Nächster Auftritt – Datum
            type: text
            width: 1/2
          upcoming_location:
            label: Nächster Auftritt – Ort
            type: text
            width: 1/2
          upcoming_description:
            label: Nächster Auftritt – Beschreibung
            type: textarea
            size: medium
          highlight_cards:
            label: Themenblöcke
            type: structure
            columns:
              title:
                width: 1/3
              text:
                width: 2/3
            fields:
              title:
                label: Titel
                type: text
              text:
                label: Text
                type: textarea
                size: small
          body:
            label: Freier Text
            type: textarea
            size: huge

  - width: 1/3
    sections:
      hero_media:
        type: files
        headline: Portrait / Medien
        layout: cards
        template: portrait
      subpages:
        type: pages
        headline: Unterseiten
        template: default
